Update README.md
AgoraIO-Community/AI-in-RTC_ProgrammingChallenge pull request #3
Opened 2019-08-19 06:24 UTC by Kingzhoudk

Update README.md

2019-08-19 06:47 UTC, plutoless commented on ChallengeProject/JLingWeb/JLingWeb/settings.py
> +        'PORT': '3306',
确定一下是否安全

2019-08-19 06:48 UTC, plutoless requested changes
.pyc之类的编译文件不要交上来

2019-08-19 07:05 UTC, Kingzhoudk commented
好的好的，不小心就一起提交上来了，我注意一下 

发送自 Windows 10 版邮件应用

发件人: Qianze Zhang
发送时间: 2019年8月19日 14:47
收件人: AgoraIO-Community/AI-in-RTC_ProgrammingChallenge
抄送: Kingzhoudk; Author
主题: Re: [AgoraIO-Community/AI-in-RTC_ProgrammingChallenge] JLing家庭管家 (#3)

@plutoless commented on this pull request.

In ChallengeProject/JLingWeb/JLingWeb/settings.py:
> +]

+

+WSGI_APPLICATION = 'JLingWeb.wsgi.application'

+

+

+# Database

+# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

+

+DATABASES = {

+    'default': {

+        'ENGINE': 'django.db.backends.mysql',

+        'NAME': 'JLing',

+        'USER': 'test',

+        'PASSWORD': '123456',

+        'HOST': '47.107.56.104',

+        'PORT': '3306',

确定一下是否安全
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-07 10:00 UTC, Kingzhoudk commented
有点乱

2024-11-14 21:21 UTC, closed without merging